<?php
    return [
        "IN-MP" => "MADHYA PRADESH",
        "IN-AN" => "ANDAMAN AND NICOBAR",
        "IN-AP" => "ANDHRA PRADESH",
        "IN-AR" => "ARUNACHAL PRADESH",
        "IN-AS" => "ASSAM",
        "IN-BR" => "BIHAR",
        "IN-CH" => "CHANDIGARH",
        "IN-CT" => "CHHATTISGARH",
        "IN-DN" => "DADRA AND NAGER HAVELI",
        "IN-DD" => "DAMAN AND DIU",
        "IN-GA" => "GOA",
        "IN-GJ" => "GUJARAT",
        "IN-HR" => "HARYANA",
        "IN-HP" => "HIMACHAL PRADESH",
        "IN-JK" => "JAMMU AND KASHMIR",
        "IN-JH" => "JHARKHAND",
        "IN-KA" => "KARNATAKA",
        "IN-KL" => "KERALA",
        "IN-LD" => "LAKSHADWEEP",
        "IN-MH" => "MAHARASHTRA",
        "IN-MN" => "MANIPUR",
        "IN-ML" => "MEGHALAYA",
        "IN-MZ" => "MIZORAM",
        "IN-NL" => "NAGALAND",
        "IN-ND" => "NEW DELHI",
        "IN-PY" => "PONDICHERRY",
        "IN-PB" => "PUNJAB",
        "IN-RJ" => "RAJASTHAN",
        "IN-SK" => "SIKKIM",
        "IN-TN" => "TAMILNADU",
        "IN-TR" => "TRIPURA",
        "IN-UP" => "UTTAR PRADESH",
        "IN-UT" => "UTTARANCHAL",
        "IN-WB" => "WEST BENGAL",
        "IN-OR" => "ODISHA"
    ];
